---
title: "Understanding the COVID-19 pandemic through data"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    css: R-shiny-style-changes.css
---
  
```{r setup, include=FALSE}
source("styles.R")
source("00_setup.R")

library(pins)
library(RColorBrewer)
library(plyr)
library(ggiraph)
library(patchwork)
library(cowplot)

my_key <- Sys.getenv("connect_key")
my_server <- "http://localhost:3939/"

# UNCOMMENT FOR LOCAL USE with EXTERNAL server:
# my_key <- Sys.getenv("connect_key_ext")
# my_server <- "http://w0lxopshyprd1b.worldbank.org:3939/" # External server

# UNCOMMENT FOR LOCAL USE with INTERNAL server:
  my_key <- Sys.getenv("connect_key_int")
  my_server <- "http://w0lxpjekins05.worldbank.org:3939/" # Internal server

board_register_rsconnect(key    = my_key,
                         server = my_server)

dfm <- pin_get("dfm", board = "rsconnect")
ccc <- pin_get("ccc", board = "rsconnect")
fullcd2 <- pin_get("fullcd2", board = "rsconnect")
treemap <- pin_get("treemap_data", board = "rsconnect")
wld_data <- pin_get("wld_data", board = "rsconnect")
indicator_list <- pin_get("indicator_list", board = "rsconnect")
new_c <- pin_get("new_c", board = "rsconnect")
new_wl <- pin_get("new_wl", board = "rsconnect")
#cg_data <- pin_get("cg_data", board = "rsconnect")
age_pop <- pin_get("age_pop", board = "rsconnect")
age_pop <- age_pop$age_pop
covid <- pin_get("covid", board = "rsconnect")
covid <- covid$covid
covid <- c( "COVID-19 Cases: Case Fatality Rate",
            "COVID-19 Cases: Confirmed",
            "COVID-19 Cases: Confirmed (log scale)",
            "COVID-19 Cases: Confirmed (per 1,000 people)",
            "COVID-19 Cases: Confirmed (per 1,000 people, log scale)",
            "COVID-19 Cases: Deaths",
            "COVID-19 Cases: Deaths (log scale)",
            "COVID-19 Cases: Deaths (per 1,000 people)",
            "COVID-19 Cases: Deaths (per 1,000 people, log scale)",
            "COVID-19 Cases: New Confirmed cases (Daily)",
            "COVID-19 Cases: New Deaths (Daily)")
covidlog <- covid[stringr::str_detect(covid, "log scale")]
covidbubble <- covid[!stringr::str_detect(covid, "log scale")]
covid_treemap <- covid[!stringr::str_detect(covid, paste(c("log scale", "Fatality", "per 1,000 people"),collapse = '|'))]
health <- pin_get("health", board = "rsconnect")
health <- health$health
water <- pin_get("water", board = "rsconnect")
water <- water$water


my_date <- max(wld_data$date)
my_date2 <- format(as.Date(my_date), format = "%b %d")
my_date2 <- as.character(my_date2)
today <- as.Date(my_date) + 1

#--------- filtered cases
covid <- grep("(Confirmed|Deaths)", covid, value = TRUE)


#------country palette
#This has to be done here and not in utils because Ineed the `fullcd2` dataframe

uniq_cty <- unique(fullcd2$`Short Name`)

cty_color <-  setNames(
  rep(palette, ceiling(length(uniq_cty)/length(palette)))[1:length(uniq_cty)],
  uniq_cty
)


## pop age structure data
indicators1 <- c("SP.POP.0004.MA.5Y", "SP.POP.1014.MA.5Y", "SP.POP.0509.MA.5Y",
                 "SP.POP.1519.MA.5Y", "SP.POP.2024.MA.5Y", "SP.POP.2529.MA.5Y",
                 "SP.POP.3034.MA.5Y", "SP.POP.3539.MA.5Y", "SP.POP.4044.MA.5Y",
                 "SP.POP.4549.MA.5Y", "SP.POP.5054.MA.5Y", "SP.POP.5559.MA.5Y",
                 "SP.POP.6064.MA.5Y", "SP.POP.6569.MA.5Y", "SP.POP.7074.MA.5Y",
                 "SP.POP.7579.MA.5Y", "SP.POP.80UP.MA.5Y")

indicators2 <- c("SP.POP.0004.FE.5Y",  "SP.POP.1014.FE.5Y", "SP.POP.0509.FE.5Y",
                 "SP.POP.1519.FE.5Y", "SP.POP.2024.FE.5Y", "SP.POP.2529.FE.5Y",
                 "SP.POP.3034.FE.5Y", "SP.POP.3539.FE.5Y", "SP.POP.4044.FE.5Y",
                 "SP.POP.4549.FE.5Y", "SP.POP.5054.FE.5Y", "SP.POP.5559.FE.5Y",
                 "SP.POP.6064.FE.5Y", "SP.POP.6569.FE.5Y", "SP.POP.7074.FE.5Y",
                 "SP.POP.7579.FE.5Y", "SP.POP.80UP.FE.5Y")

indicators <- c("SP.POP.TOTL.MA.IN", "SP.POP.TOTL.FE.IN")

dt1 <- wb(
  indicator = indicators1,
  startdate = 2018,
  enddate = 2018,
  return_wide = FALSE
  )

dt2 <- wb(
  indicator = indicators2,
  startdate = 2018,
  enddate = 2018,
  return_wide = FALSE
)

dt3 <- wb(
  indicator = indicators,
  startdate = 2018,
  enddate = 2018,
  return_wide = TRUE
) %>%
  select("iso3c", "SP.POP.TOTL.MA.IN", "SP.POP.TOTL.FE.IN")

  dt1 <- merge(dt1, dt3, "iso3c")
  dt1$value2 <- (dt1$value * dt1$SP.POP.TOTL.MA.IN)/100

  dt2 <- merge(dt2, dt3, "iso3c")
  dt2$value2 <- (dt1$value * dt1$SP.POP.TOTL.FE.IN)/100

  dt <- rbind(dt1, dt2)

  dt$gender <- substr(dt$indicatorID, 13, 14)
  dt$startage <- substr(dt$indicatorID, 8, 9)
  dt$endage <- substr(dt$indicatorID, 10, 11)
  dt$age <- paste0(dt$startage, "-", dt$endage)
  dt$age[dt$age == "80-UP"] <- "80+"

  dt$age <- as.factor(dt$age)

  dt$value3 <- ifelse(dt$gender == "MA", dt$value2*-1, dt$value2)

  ## income region and world level data
indicators <- as.character(indicator_list$code)

ing <- wb(
  c("LIC", "LMC", "UMC", "HIC", "SSF", "SAS", "NAC", "ECS", "LCN", "MEA", "EAS"),
  indicator = indicators,
  startdate = 1990,
  enddate = 2019,
  return_wide = TRUE,
) %>%
  select(-iso2c)

inm <- melt(ing)

int <- inm %>%
  filter(!is.na(value)) %>%
  group_by(variable) %>%
  filter(date == max(date))

```


Indicators
=====================================
  
Sidebar { .sidebar data-width=250}
-----------------------------------------------------------------------
Last Updated on: `r today`

```{r}

selectInput("variable",
            "Indicator Y-axis:",
            choices = list(
              `Age & Population` = age_pop,
              `COVID-19` = covid,
              Health = health,
              `Water & Sanitation` = water),  
            selected = "COVID-19 Cases: Deaths"
)    

selectInput("variable2",
            "Indicator X-axis:",
            choices = list(
              `Age & Population` = age_pop,
              `COVID-19` = covid,
              Health = health,
              `Water & Sanitation` = water),                
            selected = "Population ages 65 and above (% of total)"
) 

#selectInput("size",
#            "Bubble size:",
#            choices = covidbubble,                
#            selected = "COVID-19 Cases: Confirmed"
#) 

radioButtons("color",
             "Bubble color (click on legend items to exclude selected category):",
             choices = c("Income Group", "Region"),  
             selected = "Income Group"
) 

selectizeInput("Country Name",
               "Country (compare countries over time):",
               c(unique(as.character(dfm$`Short Name`))),
               multiple = TRUE, 
               options = list(maxItems = 12),
               selected = c("China", "Italy", "United States", "Spain", "Germany", "France")
)
```

Row  {data-height=130}
-----------------------------------------------------------------------
### World
```{r}
renderValueBox({
  con <- wld_data %>%
    filter(wld_data$date == max(wld_data$date)) %>%
    pull(`COVID-19 cases: Confirmed`) 
  con <- format(con, big.mark=",")
  de <- HTML(paste0("Total cases:<br/>", con))
  valueBox(tags$p(de, style = "font-size: 80%;")
           #, 
           #icon = "fa-users"
  )
})
```

### World
```{r}
renderValueBox({
  con <- new_wl %>% 
    filter(status == "Confirmed") %>% 
    pull(con) %>% 
    format(big.mark = ",")
  
  de <- HTML(paste0("New cases (", my_date2, "):<br/>", con))
  #de <- str_wrap(de, 15)
  valueBox(tags$p(de, style = "font-size: 80%;")
           #, 
           #icon = "fa-users"
  )
})
```

### World
```{r}
renderValueBox({
  con <- wld_data %>%
    filter(wld_data$date == max(wld_data$date)) %>%
    pull(`COVID-19 cases: Deaths`) %>%
    format(big.mark = ",")
  
  de <- HTML(paste0("Total deaths:<br/>", con))
  valueBox(tags$p(de, style = "font-size: 80%;")
           #, 
           #icon = "fa-users"
  )
})
```

Row  {data-height=500}
-----------------------------------------------------------------------
  
### Explore relationships
```{r}
renderPlotly ({
  
  df2 <- dfm[dfm$date == 2019 & dfm$variable %in% input$variable, ]
  df3 <- dfm[dfm$date == 2019 & dfm$variable %in% input$variable2, c(1, 6)]
  #dfs <- dfm[dfm$date == 2019 & dfm$variable %in% "COVID-19 Cases: Deaths", c(1, 6)]
   
  #  dfs <- dfs %>%
  #        rename("siz" = "mrv")

     
    df3 <- df3 %>%
          dplyr::rename("mrv2" = "mrv")
  
    df4 <- merge(df2, df3, by = c("iso3c"))   
  #  df4 <- merge(df4, dfs, by = c("iso3c"))  
  
    m <- df4[df4$`Short Name` %in% input$`Country Name`,]
    a <- list(x = m$mrv2, y = m$mrv,
              text = m$`Short Name`, 
              xref = "x", 
              yref = "y",
              showarrow = TRUE, 
              arrowhead = 0, 
              ax = 20, 
              ay = -40, 
              arrowcolor= toRGB("grey80"),
              font = list(color = "dark grey", size = 14)
              )
    
    
     texty <- paste("</br>", df4$`Short Name`,
                    "</br>X: ", round(df4$mrv2, 1),
                    "</br>Y: ", round(df4$mrv, 1))
     
    
    df4$`Income Group` <- ordered(df4$`Income Group`, 
                                  levels = c("Low income", 
                                             "Lower middle income",
                                             "Upper middle income", 
                                             "High income"))
    
    if (input$color == "Income Group"){
    df4$colort <- df4$`Income Group`
  } else {
    df4$colort <- df4$Region
  }
    
      if (input$color == "Income Group"){
    colorpal <- inc_color
  } else {
    colorpal <- brewer.pal(7, "Paired")
  }  

    plot_ly(data = df4) %>%
      add_trace(
        x = ~ mrv2,
        y = ~ mrv,
        type = 'scatter',
        mode = 'markers',
        color =  ~colort,
        colors = ~colorpal,
        opacity = 0.9,
        size   = 15,
      #  sizes  = c(20, 100),
      hoverinfo = 'text',
      text = ~ texty
      ) %>%
    #add_annotations(text = df4$lab, textfont = list(size = 14),
    #         textposition = "top right") %>% 
      layout(legend = list(x = 0, 
                           y = -0.3, 
                           orientation = 'h'
                           ),
             annotations = a,
             xaxis = list(type = if_else(input$variable2 %in% covidlog, "log", "linear"),
                          zeroline = FALSE, 
                          showline = FALSE, 
                          showgrid = TRUE, 
                          title = str_wrap((input$variable2), 40),
                          range = c(min(df4$variable), max(df4$variable))
                          ),
             yaxis = list(type = if_else(input$variable %in% covidlog, "log", "linear"),
                          zeroline = FALSE, 
                          showline = FALSE, 
                          showgrid = TRUE, 
                          title = str_wrap(input$variable, 40),
                          range = c(min(df4$variable), max(df4$variable))
                          )
             )
      })
```


### Compare countries over time
```{r}

uiOutput("dynamic")

output$dynamic <- renderUI({ 
  if (input$variable %in% covid){
    plotlyOutput("plot1")
  } else {
    plotlyOutput("plot2")
  }
})

output$plot1 <- renderPlotly({
  
  dft <- fullcd2[fullcd2$`Short Name` %in% input$`Country Name`
                 & fullcd2$variable %in% input$variable,]
  
dft <- dft    %>%
  arrange(date) %>% 
  group_by(Region) %>% 
  mutate(
    op = match(name, unique(name)), 
    opacity = (1-(op/max(op))+1/max(op)),
  ) %>% 
  ungroup() %>% 
  mutate(
    colors = rep(palette, ceil(nrow(.)/length(palette)))[1:nrow(.)]
  )  
  
  
  texty <- paste("</br>", dft$`Short Name`,
                 "</br>Y: ", round(dft$value, 2), 
                 "</br>Date: ", dft$date)
  
  plot_ly(data = dft,
          x = ~date,
          y = ~ value ) %>%
    add_trace(

      name  = ~ `Short Name`, 
      type  = 'scatter',
      mode  = 'lines+markers', 
      color = ~`Short Name`,
      colors = brewer.pal(12, "Paired"),
      hoverinfo = 'text',
      text = ~ texty
    ) %>%
    layout(
      legend = list(orientation = 'h'),
      xaxis = list(
        title = '',
        zeroline = FALSE,
        showline = FALSE,
        showgrid = TRUE
      ),
      yaxis = list(type = if_else(input$variable %in% covidlog, "log", "linear"),
        title = input$variable,
        zeroline = FALSE,
        showline = FALSE,
        showgrid = TRUE
      )
    )
  
})

output$plot2 <- renderPlotly({
  
  df1 <- dfm[dfm$`Short Name` %in% input$`Country Name` 
             & dfm$variable %in% input$variable,]
  
  df1 <- df1 %>%
    group_by(iso3c) %>%
    arrange(date) %>%
    mutate(date = as.numeric(date)) %>% 
    ungroup() %>% 
    mutate(
      colors = rep(palette, ceil(nrow(.)/length(palette)))[1:nrow(.)]
    )

  
  texty <- paste("</br>", df1$`Short Name`,
                 "</br>Y: ", round(df1$value, 1), 
                 "</br>Year: ", df1$date)
  
  plot_ly(df1) %>%
    add_trace(
      x = ~ date,
      y = ~ value,
      name = ~ `Short Name`,
      type = 'scatter',
      mode = 'lines+markers',
      color = ~`Short Name`,
      colors = brewer.pal(12, "Paired"),
      hoverinfo = 'text',
      text = ~ texty
    ) %>%
    layout(legend = list(orientation = 'h'),
           xaxis = list(title = '', 
                        zeroline = FALSE, 
                        showline = FALSE, 
                        showgrid = TRUE
           ), 
           yaxis = list(title = str_wrap(input$variable, 40), 
                        zeroline = FALSE, 
                        showline = FALSE, 
                        showgrid = TRUE
           )
    )
  
})

```

COVID-19 Case Data
=====================================
  
Sidebar { .sidebar data-width=250}
-----------------------------------------------------------------------
Last Updated on: `r today`
  
```{r}

radioButtons("var",
             "",
             choices = covid_treemap,  
             selected = "COVID-19 Cases: Confirmed"
)  


getind <- reactive({
  input$var
})

```

Row
-----------------------------------------------------------------------
### `r renderText(getind())`
  
```{r}
renderPlotly({
  
  tmp <- treemap %>%
    filter(variable %in% input$var,
           date == max(date, na.rm = TRUE)) %>%
  #   filter(variable %in% input$var)
  # tmp$value[tmp$ids == "World"] <- tmp$value[tmp$ids == "World" & tmp$date == max(tmp$date, na.rm = TRUE)]
  # tmp <- tmp %>%
  #   filter(date == input$date) %>%
    left_join(color_map2, by = c("labels" = "Region")) 
  
  tmp %>% plot_ly(
    type ='treemap',
    ids =  ~ids,
    labels = ~labels,
    parents = ~parents,
    values = ~ value,
    branchvalues = "total",
    marker  = list(colors = ~color),
    domain = list(column=0))# %>% 
    # add_trace(
    #   branchvalues = "total"
    # )
  
})


```


### `r renderText(getind())`

```{r}

renderPlotly({
  
  dfb <- fullcd2 %>% 
    filter(date == max(date),
           variable %in% input$var) %>%
    arrange(desc(value))  %>%
    mutate(`Short Name` = fct_reorder(`Short Name`, desc(value))) %>% 
    slice(1:20)
  
  texty <- paste("</br>", dfb$`Short Name`,
                 "</br>Y: ", dfb$value, 
                 "</br>Date: ", dfb$date)
  
  plot_ly(dfb, 
          type = 'bar', 
          x = ~`Short Name`, 
          y = ~value, 
          color = ~Region,
          colors = reg_color,
          hoverinfo = 'text',
          text = ~ texty
  ) %>% 
    layout(
      legend = list(orientation = 'h', 
                    y = 100, 
                    x = 0),
      xaxis = list(title = '', 
                   zeroline = FALSE, 
                   showline = FALSE, 
                   showgrid = TRUE
      ), 
      yaxis = list(title = '', 
                   zeroline = FALSE, 
                   showline = FALSE, 
                   showgrid = TRUE
      )
    )
})


```

Country Profile
=====================================
  Sidebar { .sidebar data-width=250}
-----------------------------------------------------------------------
  Last Updated on: `r today`

```{r}

selectInput("countryn",
            "Country:",
            choices = c(unique(as.character(dt$country))),
            selected = "United States"
)

```

Row {.tabset}
-----------------------------------------------------------------------
### Populations at risk
```{r} 

#dtl <- dt[(dt$country == input$countryn), ]
dtl <- dt[dt$country == "United States",]

con <- dfm %>%
   filter(variable == "Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)") %>%
  group_by(iso3c) %>%
  filter(mry == max(mry, na.rm = T)) %>%
  select("iso3c", "variable", "mrv", "Income Group", "Region", "Short Name") %>%
  dplyr::rename("value" = "mrv")

#con$indicator <- "SH.DYN.NCOM.ZS

renderGirafe({
  
  n1 <- ggplot(dtl, aes(x = age, y = value3, fill = gender)) + 
    geom_bar_interactive(subset = plyr::.(gender == "FE"), stat = "identity",
                         aes(tooltip = value3)) + 
    geom_bar_interactive(subset = plyr::.(gender == "MA"), stat = "identity",
                         aes(tooltip = value3)) + 
    # scale_y_continuous(breaks = seq(-15000000, 15000000, 5000000), 
    #                   labels = paste0(as.character(c(seq(15, 0, -5), seq(5, 15, 5))), "m")) + 
    coord_flip() + 
    scale_fill_brewer(palette = "Set1") + 
    theme_bw()
  
  f <- ggplot(con, aes(x=value, y=`Income Group`, 
                       color= ifelse(con$iso3c == "USA", "green", "grey"),
                       size = 8))  + 
    theme_bw() +
  geom_point_interactive(tooltip = con$value)
  
  
    t <- girafe(ggobj = plot_grid(n1, f, ncol = 1),
          width_svg = 24, 
          height_svg = 16)

   t
  
})

## add the CVD indicator
   
   
```


### Health systems capacity
```{r}

#cm <- dfm[(dfm$`Short Name` %in% input$Country2),]

#cm <- dfm[dfm$`Short Name` %in% input$Country2,]
cm <- dfm[dfm$`Short Name` %in% "United States",]

con1 <- cm %>%
   filter(variable == "UHC service coverage index" | variable == "Current health expenditure per capita, PPP (current international $)") %>%
#  filter(`Short Name` == "United States") %>%
  group_by(variable) %>%
  filter(mry == max(mry, na.rm = T)) %>%
  select("iso3c", "variable", "mrv", "Income Group", "Region") %>%
  dplyr::rename("value" = "mrv")

con1$indicator <- ifelse(con1$variable == "UHC service coverage index", "SH.UHC.SRVS.CV.XD",
                        "SH.XPD.CHEX.PP.CD")

con2 <- cm %>%
   filter(variable == "Physicians (per 1,000 people)" | variable == "Nurses and midwives (per 1,000 people)") %>%
#  filter(`Short Name` == "United States") %>%
  group_by(variable) %>%
  filter(mry == max(mry, na.rm = T)) %>%
  select("iso3c", "variable", "mrv", "Income Group", "Region") %>%
  dplyr::rename("value" = "mrv")

con2$indicator <- ifelse(con2$variable == "Physicians (per 1,000 people)", "SH.MED.PHYS.ZS",
                        "SH.MED.NUMW.P3")

h1 <- int %>%
  filter(country == con1$`Income Group`[1] | country == con1$Region[1]) %>%
  filter(variable == "SH.XPD.CHEX.PP.CD" | variable == "SH.UHC.SRVS.CV.XD") %>%
  select("iso3c", "variable", "value") %>%
  dplyr::rename("indicator" = "variable")

h2 <- int %>%
  filter(country == con2$`Income Group`[1] | country == con2$Region[1]) %>%
  filter(variable == "SH.MED.PHYS.ZS" | variable == "SH.MED.NUMW.P3") %>%
  select("iso3c", "variable", "value") %>%
  dplyr::rename("indicator" = "variable")

h1 <- rbind(h1, con1)
h2 <- rbind(h2, con2)

renderGirafe({

     p1 <- ggplot(data=h1, aes(x=iso3c, y=value)) +
     geom_bar_interactive(stat="identity",
                          aes(tooltip = iso3c))  + 
    theme_bw() +
     facet_wrap(~indicator, scales = "free")

      p2 <- ggplot(h2, aes(fill=indicator, y=value, x=iso3c)) +
     geom_bar_interactive(position="dodge", stat="identity",
                          aes(tooltip = iso3c))  + 
    theme_bw()


   p <- girafe(ggobj = plot_grid(p1, p2, ncol = 1),
          width_svg = 24, 
          height_svg = 16)

   p

})

```
